In [70]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [71]:
import pandas as pd
dataset_path = 'multi_domain_sentiment_reviews.csv'
df = pd.read_csv(dataset_path)

print(df.shape)
df.head()

(6000, 11)

,unique_id,asin,product_name,product_type,helpful,rating,title,date,reviewer,reviewer_location,review_text
0,0760320799:ok_-_but_you_didn't_tell_the_whole_...,0760320799,Burning Cold: The Cruise Ship Prinsendam and t...,books,4 of 4,2.0,OK - but you didn't tell the whole story,"March 29, 2006",A. Kienitz,NaN,"I was there, as were several of my fellow Sitk..."
1,B0007VMROE:bad_product__/_bad_company:j._hill,B0007VMROE,Palm Tungsten E2 Handheld: Electronics,electronics,11 of 12,1.0,BAD PRODUCT / BAD COMPANY,"October 3, 2006",J. Hill,NaN,This is the third Palm PDA I have owned. I bo...
2,0972488928:worth_every_bit_of_the_$10_selling_...,0972488928,How to Make Money in Stocks: A Winning System ...,books,0 of 3,5.0,Worth Every Bit of the $10 Selling Price,"April 22, 2006",Dennis R. Jugan,"Johnstown, PA United States","Are you ready to become a ""home gamer."" Are y..."
3,B000028F42:dual_voltage_/__dual_wattage:r._bou...,B000028F42,Recoton ADF1650 50/1600W Dual Wattage Travel C...,electronics,5 of 5,4.0,dual voltage / dual wattage,"July 12, 2006","R. BOUGIE ""the boogie man""","CT, USA",worked very well as planed\njust heavy to carr
4,B00005MF9U:don't...:m._bowen,B00005MF9U,LitterMaid LM900 Self-Cleaning Litter Box: Kit...,kitchen & housewares,1 of 1,1.0,Don't...,"November 24, 2006",M. Bowen,NaN,I had a littermaid a couple of years ago that ...

In [72]:
df.drop(columns=['unique_id','asin','reviewer','date','reviewer_location'],axis=1,inplace=True)

In [73]:
df[['helpful_votes', 'total_votes']] = df['helpful'].str.split(' of ', expand=True)

df['helpful_votes'] = pd.to_numeric(df['helpful_votes'], errors='coerce')
df['total_votes'] = pd.to_numeric(df['total_votes'], errors='coerce')

df['helpfulness_ratio'] = df['helpful_votes'] / df['total_votes']

df['helpfulness_ratio'] = df['helpfulness_ratio'].fillna(0)

df['helpful_votes'] = df['helpful_votes'].fillna(0)
df['total_votes'] = df['total_votes'].fillna(0)

df = df.drop(columns=['helpful'])

In [74]:
df = df[df['product_type'] != 'computer & video games']

In [75]:
df['rating'].value_counts()

rating
1.0    2009
5.0    1956
2.0    1108
4.0     926
Name: count, dtype: int64

In [76]:
df['label'] = df['rating'].apply(lambda x: 1 if x >= 4 else 0)

In [77]:
df = pd.get_dummies(df, columns=['product_type'])

In [78]:
df['product_type_kitchen & housewares'] = df['product_type_kitchen & housewares'].astype(int)
df['product_type_electronics'] = df['product_type_electronics'].astype(int)
df['product_type_books'] = df['product_type_books'].astype(int)

In [79]:
df

,product_name,rating,title,review_text,helpful_votes,total_votes,helpfulness_ratio,label,product_type_books,product_type_electronics,product_type_kitchen & housewares
0,Burning Cold: The Cruise Ship Prinsendam and t...,2.0,OK - but you didn't tell the whole story,"I was there, as were several of my fellow Sitk...",4.0,4.0,1.000000,0,1,0,0
1,Palm Tungsten E2 Handheld: Electronics,1.0,BAD PRODUCT / BAD COMPANY,This is the third Palm PDA I have owned. I bo...,11.0,12.0,0.916667,0,0,1,0
2,How to Make Money in Stocks: A Winning System ...,5.0,Worth Every Bit of the $10 Selling Price,"Are you ready to become a ""home gamer."" Are y...",0.0,3.0,0.000000,1,1,0,0
3,Recoton ADF1650 50/1600W Dual Wattage Travel C...,4.0,dual voltage / dual wattage,worked very well as planed\njust heavy to carr,5.0,5.0,1.000000,1,0,1,0
4,LitterMaid LM900 Self-Cleaning Litter Box: Kit...,1.0,Don't...,I had a littermaid a couple of years ago that ...,1.0,1.0,1.000000,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...
5995,Philips HN060/37 Noise-Canceling Earbuds: Elec...,2.0,Noise Canceling decent; music sound bad,If you're not that picky about sound quality w...,1.0,1.0,1.000000,0,0,1,0
5996,Capresso 112.05 EspressoPro ThermoBlock Pump E...,2.0,Great Frother - espresso consistently inconsis...,The frother is great! Easy to use etc. The e...,0.0,0.0,0.000000,0,0,0,1
5997,LitterMaid LM900 Self-Cleaning Litter Box: Kit...,1.0,High price but cheap parts,The Littermaid Mega is absolutely one of the w...,1.0,2.0,0.500000,0,0,0,1
5998,Hoffritz Stainless Steel Tube Baster: Kitchen ...,1.0,Bulb is Weak Link,Bought this item last Christmas for my wife. W...,12.0,12.0,1.000000,0,0,0,1
5999,Frozen Assets Lite and Easy: How to Cook for a...,5.0,Great for Veteran freezer cooks!,If you have been freezer cooking for awhile or...,11.0,11.0,1.000000,1,1,0,0

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5999 entries, 0 to 5999
Data columns (total 11 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   product_name                       5999 non-null   object
 1   rating                             5999 non-null   float64
 2   title                              5999 non-null   object
 3   review_text                        5999 non-null   object
 4   helpful_votes                      5999 non-null   float64
 5   total_votes                        5999 non-null   float64
 6   helpfulness_ratio                  5999 non-null   float64
 7   label                              5999 non-null   int64
 8   product_type_books                 5999 non-null   int32
 9   product_type_electronics           5999 non-null   int32
 10  product_type_kitchen & housewares  5999 non-null   int32
dtypes: float64(4), int32(3), int64(1), object(3)
memory usage: 492.1+ KB

In [81]:
df.columns

Index(['product_name', 'rating', 'title', 'review_text', 'helpful_votes',
       'total_votes', 'helpfulness_ratio', 'label', 'product_type_books',
       'product_type_electronics', 'product_type_kitchen & housewares'],
      dtype='object')

In [82]:
import re
from nltk.stem import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

df['title'] = df['title'].str.lower().str.strip()
df['review_text'] = df['review_text'].str.lower().str.strip()
df['product_name'] = df['product_name'].str.lower().str.strip()

stemmer = PorterStemmer()
def preprocess_text(text):
    text = re.sub(r'[^a-z\s]', '', text)
    text = ' '.join([stemmer.stem(word) for word in text.split()])
    return text

df['title'] = df['title'].apply(preprocess_text)
df['review_text'] = df['review_text'].apply(preprocess_text)
df['product_name'] = df['product_name'].apply(preprocess_text)

df['combined_text'] = df['title'] + ' ' + df['review_text'] + ' ' + df['product_name']

tfidf_vectorizer = TfidfVectorizer(stop_words='english', max_features=5000)

X = tfidf_vectorizer.fit_transform(df['combined_text'])

transformed_df = pd.DataFrame(
    X.toarray(), 
    columns=tfidf_vectorizer.get_feature_names_out()
)

y = df['label']
X_train, X_test, y_train, y_test = train_test_split(transformed_df, y, test_size=0.2, random_state=5)
clf = RandomForestClassifier(n_estimators=100, random_state=5)
clf.fit(X_train, y_train)

importances = clf.feature_importances_

feature_importances = pd.DataFrame({'feature': transformed_df.columns, 'importance': importances})

feature_importances = feature_importances.sort_values(by='importance', ascending=False)

feature_importances.head(20)

         feature  importance
1917       great    0.017589
3679      return    0.010340
1218  disappoint    0.009909
1526       excel    0.008805
1371        easi    0.008618
4804          wa    0.008421
2632        love    0.007923
4835        wast    0.007420
3309        poor    0.006175
3199     perfect    0.006154
382         best    0.006085
298          bad    0.006051
4600         tri    0.005579
3383       price    0.005232
4469         thi    0.004694
1273      doesnt    0.004482
1408    electron    0.004185
2851       month    0.003862
1882        good    0.003578
1192         did    0.003524

In [83]:
top_features = feature_importances.head(20)['feature']

X_top_features = transformed_df[top_features]

df_reduced = df.drop(columns=['title', 'review_text','product_name','combined_text'])

df_final = pd.concat([df_reduced, X_top_features], axis=1)
df_final.head()

,rating,helpful_votes,total_votes,helpfulness_ratio,label,product_type_books,product_type_electronics,product_type_kitchen & housewares,great,return,...,best,bad,tri,price,thi,doesnt,electron,month,good,did
0,2.0,4.0,4.0,1.000000,0.0,1.0,0.0,0.0,0.000000,0.000000,...,0.000000,0.061295,0.051654,0.000000,0.067572,0.0,0.000000,0.0,0.040368,0.055838
1,1.0,11.0,12.0,0.916667,0.0,0.0,1.0,0.0,0.000000,0.000000,...,0.000000,0.143261,0.000000,0.000000,0.052644,0.0,0.042173,0.0,0.000000,0.000000
2,5.0,0.0,3.0,0.000000,1.0,1.0,0.0,0.0,0.000000,0.069588,...,0.060857,0.067060,0.000000,0.061745,0.049285,0.0,0.000000,0.0,0.044165,0.000000
3,4.0,5.0,5.0,1.000000,1.0,0.0,1.0,0.0,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.095504,0.0,0.000000,0.000000
4,1.0,1.0,1.0,1.000000,0.0,0.0,0.0,1.0,0.098491,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.108716,0.0,0.000000,0.0,0.000000,0.134756

In [85]:
df_final = df_final.dropna()
df_final.drop(columns=['rating'],axis=1,inplace=True)

In [86]:
y = df_final['label']
X = df_final.drop(columns=['label'],axis=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=5)
clf2 = RandomForestClassifier(n_estimators=100, random_state=5)
clf2.fit(X_train, y_train)

importances2 = clf2.feature_importances_

feature_importances = pd.DataFrame({'feature': X.columns, 'importance': importances2})

feature_importances = feature_importances.sort_values(by='importance', ascending=False)

feature_importances.head(20)

              feature  importance
20                thi    0.124773
1         total_votes    0.082589
2   helpfulness_ratio    0.078898
11                 wa    0.070293
22           electron    0.069337
6               great    0.061039
0       helpful_votes    0.057992
24               good    0.050198
12               love    0.036860
18                tri    0.033755
16               best    0.028468
10               easi    0.026482
21             doesnt    0.025500
25                did    0.024861
7              return    0.024161
19              price    0.024147
23              month    0.022100
9               excel    0.021694
8          disappoint    0.020454
17                bad    0.020165

In [96]:
col = feature_importances.head(25)['feature']

In [97]:
df_to_train = df_final[col]

In [98]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import accuracy_score
from xgboost import XGBClassifier

X = df_to_train
y = df_final['label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=5)

param_grid = {
    'learning_rate': [0.01,0.02,0.03], 
    'max_depth': [1,3, 5, 7],            
    'n_estimators': [100, 300,500],   
    'subsample': [0.2,0.3,0.4,0.5,0.6],          
    'colsample_bytree': [0.2,0.3,0.4,0.5,0.6]    
}

xgb = XGBClassifier(objective='binary:logistic', eval_metric='logloss')

random_search = RandomizedSearchCV(estimator=xgb,
                                   param_distributions=param_grid,
                                   n_iter=50, 
                                   scoring='accuracy',
                                   cv=5, 
                                   verbose=1,
                                   n_jobs=-1) 

random_search.fit(X_train, y_train)

print("Best parameters found: ", random_search.best_params_)

best_model = random_search.best_estimator_
best_model.fit(X_train, y_train)

y_pred = best_model.predict(X_test)
print("Accuracy on test set: ", accuracy_score(y_test, y_pred))

Fitting 5 folds for each of 50 candidates, totalling 250 fits
Best parameters found:  {'subsample': 0.2, 'n_estimators': 300, 'max_depth': 5, 'learning_rate': 0.01, 'colsample_bytree': 0.6}
Accuracy on test set:  0.6941666666666667

In [99]:
from sklearn.metrics import classification_report, confusion_matrix

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("Classification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[454 191]
 [176 379]]
Classification Report:
              precision    recall  f1-score   support

         0.0       0.72      0.70      0.71       645
         1.0       0.66      0.68      0.67       555

    accuracy                           0.69      1200
   macro avg       0.69      0.69      0.69      1200
weighted avg       0.69      0.69      0.69      1200